/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { DependencyLink, HazardPolygon, InfrastructureAsset } from '../types/lifegrid';

export const INITIAL_ASSETS: InfrastructureAsset[] = [
  {
    id: 'SUBSTATION_N01',
    name: 'North Substation',
    type: 'power',
    lat: 13.0828,
    lon: 80.2707,
    capacity: 1.0,
    vulnerability: 0.45,
    population_served: 18000,
    criticality: 0.95,
    status: 'operational',
    disruption: 0.0,
    notes: 'Primary 230kV/110kV distribution grid feeder for Northern Municipal Sector.',
  },
  {
    id: 'SUBSTATION_S01',
    name: 'South Substation',
    type: 'power',
    lat: 13.0450,
    lon: 80.2500,
    capacity: 1.0,
    vulnerability: 0.35,
    population_served: 22000,
    criticality: 0.90,
    status: 'operational',
    disruption: 0.0,
    notes: 'South regional switching yard supplying fuel depot and southern utility lines.',
  },
  {
    id: 'PUMP_N01',
    name: 'North Water Pump',
    type: 'water',
    lat: 13.0910,
    lon: 80.2680,
    capacity: 0.9,
    vulnerability: 0.50,
    population_served: 12500,
    criticality: 0.85,
    status: 'operational',
    disruption: 0.0,
    notes: 'High-lift raw water pumping station supplying North Chennai & Metro General Hospital.',
  },
  {
    id: 'PUMP_C01',
    name: 'Central Water Station',
    type: 'water',
    lat: 13.0650,
    lon: 80.2610,
    capacity: 0.95,
    vulnerability: 0.40,
    population_served: 19500,
    criticality: 0.85,
    status: 'operational',
    disruption: 0.0,
    notes: 'Central reservoir and booster station feeding downtown clinics and Central Hospital.',
  },
  {
    id: 'HOSP_01',
    name: 'Central Hospital',
    type: 'hospital',
    lat: 13.0720,
    lon: 80.2640,
    capacity: 1.0,
    vulnerability: 0.30,
    population_served: 8500,
    criticality: 1.00,
    status: 'operational',
    disruption: 0.0,
    notes: 'Level 1 Trauma & Tertiary Emergency Healthcare Center with 450 critical care beds.',
  },
  {
    id: 'HOSP_02',
    name: 'Metro General Hospital',
    type: 'hospital',
    lat: 13.0950,
    lon: 80.2750,
    capacity: 0.85,
    vulnerability: 0.40,
    population_served: 6500,
    criticality: 0.95,
    status: 'operational',
    disruption: 0.0,
    notes: 'Suburban general hospital heavily dependent on North Pump for dialysis & sterilization.',
  },
  {
    id: 'TOWER_01',
    name: 'Telecom Relay Tower 1',
    type: 'telecom',
    lat: 13.0780,
    lon: 80.2550,
    capacity: 0.8,
    vulnerability: 0.60,
    population_served: 15000,
    criticality: 0.70,
    status: 'operational',
    disruption: 0.0,
    notes: 'Master 4G/5G and VHF emergency communications repeater mast.',
  },
  {
    id: 'ROAD_N01',
    name: 'North Arterial Corridor',
    type: 'road',
    lat: 13.0880,
    lon: 80.2720,
    capacity: 0.9,
    vulnerability: 0.55,
    population_served: 11000,
    criticality: 0.75,
    status: 'operational',
    disruption: 0.0,
    notes: 'Key multi-lane transit link connecting coastal basin to emergency hospitals.',
  },
  {
    id: 'SHELTER_01',
    name: 'Community Relief Shelter',
    type: 'shelter',
    lat: 13.0580,
    lon: 80.2680,
    capacity: 0.7,
    vulnerability: 0.25,
    population_served: 4200,
    criticality: 0.60,
    status: 'operational',
    disruption: 0.0,
    notes: 'Reinforced multipurpose flood and cyclone shelter facility.',
  },
  {
    id: 'FUEL_01',
    name: 'Strategic Fuel Depot',
    type: 'fuel',
    lat: 13.0510,
    lon: 80.2530,
    capacity: 0.9,
    vulnerability: 0.35,
    population_served: 7000,
    criticality: 0.65,
    status: 'operational',
    disruption: 0.0,
    notes: 'Municipal diesel & backup energy reserve for emergency vehicle fleet and generators.',
  },
];

export const INITIAL_DEPENDENCIES: DependencyLink[] = [
  {
    source: 'SUBSTATION_N01',
    target: 'PUMP_N01',
    type: 'electricity',
    strength: 0.95,
    criticality: 0.90,
    description: 'High-voltage feeder line powering raw water pumps.',
  },
  {
    source: 'SUBSTATION_N01',
    target: 'PUMP_C01',
    type: 'electricity',
    strength: 0.55,
    criticality: 0.80,
    description: 'Secondary grid connection for booster pumping station.',
  },
  {
    source: 'SUBSTATION_N01',
    target: 'HOSP_01',
    type: 'electricity',
    strength: 0.80,
    criticality: 1.00,
    description: 'Direct dedicated feed to Central Hospital intensive care & surgical suites.',
  },
  {
    source: 'SUBSTATION_N01',
    target: 'TOWER_01',
    type: 'electricity',
    strength: 0.75,
    criticality: 0.70,
    description: 'Power line to telecommunications tower amplifier equipment.',
  },
  {
    source: 'PUMP_N01',
    target: 'HOSP_02',
    type: 'water',
    strength: 0.85,
    criticality: 0.95,
    description: 'Pressurized water supply for hospital sanitary and dialysis units.',
  },
  {
    source: 'PUMP_C01',
    target: 'HOSP_01',
    type: 'water',
    strength: 0.65,
    criticality: 0.90,
    description: 'Treated water feeder for Central Hospital sterilization.',
  },
  {
    source: 'ROAD_N01',
    target: 'HOSP_02',
    type: 'access',
    strength: 0.70,
    criticality: 0.80,
    description: 'Primary ambulance corridor and patient logistics artery.',
  },
  {
    source: 'FUEL_01',
    target: 'HOSP_01',
    type: 'backup_fuel',
    strength: 0.35,
    criticality: 0.60,
    description: 'Emergency diesel logistics supply line for hospital on-site generators.',
  },
  {
    source: 'TOWER_01',
    target: 'HOSP_02',
    type: 'communications',
    strength: 0.40,
    criticality: 0.50,
    description: 'Radio telemetry and dispatch link for hospital ambulance control.',
  },
  {
    source: 'SUBSTATION_S01',
    target: 'FUEL_01',
    type: 'electricity',
    strength: 0.50,
    criticality: 0.50,
    description: 'Electric pumps and monitoring system at strategic fuel depot.',
  },
];

export const HAZARD_POLYGONS: HazardPolygon[] = [
  {
    id: 'HAZARD_FLOOD_NORTH',
    name: 'North Chennai River Basin Inundation Zone',
    type: 'flood',
    severity: 'severe',
    source: 'Google Earth Engine & ISRO Bhuvan Sentinel-1 SAR Composite',
    description:
      'High-risk 100-year monsoon flood corridor covering low-lying drainage channels intersecting North Substation & North Water Pump.',
    coordinates: [
      [13.1020, 80.2600],
      [13.0980, 80.2850],
      [13.0800, 80.2880],
      [13.0750, 80.2680],
      [13.0810, 80.2580],
      [13.0950, 80.2550],
    ],
  },
  {
    id: 'HAZARD_STORM_SURGE',
    name: 'Coastal Storm Surge Inundation Fringe',
    type: 'storm_surge',
    severity: 'high',
    source: 'IMD Coastal Inundation Model & Open Data India',
    description:
      'Coastal buffer subject to 1.8m surge during cyclonic events along the Bay of Bengal shoreline.',
    coordinates: [
      [13.1050, 80.2820],
      [13.1060, 80.3010],
      [13.0400, 80.2920],
      [13.0420, 80.2740],
      [13.0680, 80.2790],
      [13.0900, 80.2810],
    ],
  },
];

export const DATA_SOURCES_REGISTER = [
  {
    id: 'data-gov-in',
    name: 'India Open Government Data Platform (OGD)',
    url: 'https://data.gov.in',
    coverage: 'National / Tamil Nadu / Greater Chennai Corporation',
    description:
      'Municipal asset locations, public hospital registry, census population density aggregates, and ward administration boundaries.',
    role: 'Grounds geographic anchors, public facility context, and baseline population counts.',
  },
  {
    id: 'isro-bhuvan',
    name: 'ISRO Bhuvan Geoportal',
    url: 'https://bhuvan.nrsc.gov.in',
    coverage: 'Indian Subcontinent',
    description:
      'Thematic satellite layers, land use / land cover, terrain elevation data (CartoDEM), and disaster event mapping.',
    role: 'Provides spatial topography and historical inundation zone verification.',
  },
  {
    id: 'earth-engine',
    name: 'Google Earth Engine & Sentinel-1 SAR',
    url: 'https://earthengine.google.com',
    coverage: 'Global / Coastal India',
    description:
      'Precomputed synthetic aperture radar flood extent masks and multi-temporal water surface reflections.',
    role: 'Hazard polygon vector extraction for spatial intersection with infrastructure nodes.',
  },
  {
    id: 'imd',
    name: 'India Meteorological Department (IMD)',
    url: 'https://mausam.imd.gov.in',
    coverage: 'India Synoptic & Mesoscale Network',
    description:
      'Monsoon precipitation depth-duration frequencies, cyclonic track alerts, and storm surge thresholds.',
    role: 'Informs duration and severity scenario parameter benchmarks.',
  },
  {
    id: 'google-maps',
    name: 'Google Maps Platform',
    url: 'https://mapsplatform.google.com',
    coverage: 'Global / India Vector Maps',
    description:
      'High-resolution vector maps, Advanced Markers, Places and Routes intelligence, and geographic reference frames.',
    role: 'Interactive geospatial visualization and command center canvas.',
  },
];

export const MODELING_ASSUMPTIONS = [
  'Deterministic Cascade Simulation: Infrastructure dependencies are modeled as directed graphs where failure pressure propagates based on edge criticality and node vulnerability.',
  'Synthetic Topology Principle: Node coordinates and public facilities are grounded in real Chennai urban geography, but electrical and water utility topologies are modeled synthetically to protect critical infrastructure security.',
  'Not an Emergency Forecast: LIFEGRID AI is an exploratory decision-support platform designed for scenario testing and contingency planning. It is not an automated dispatch system.',
  'Counterfactual Isolation: Interventions (such as mobile generators) model targeted local protection (e.g. at Central Hospital) without fabricating upstream grid restoration.',
  'Additive Disruption Math: Multiple upstream dependencies accumulate disruption pressure capped at 1.0 (100% failure). Assets above 0.8 are classified as Failed; assets between 0.01 and 0.79 are classified as Degraded.',
];
